name: 'Setup Node.js env'

inputs:
  node-version:
    description: 'Node version'
    default: 20
  pnpm-version:
    description: 'PNPM version'
    default: 9

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
