name: "SDK Outdated"
description: "Reusable workflow for update the SDK packages"

inputs:
  repository:
    description: "Github Repository"
    default: ${{ github.repository }}
  changeset:
    description: "If your repository uses changesets, set this to true"
    default: false
  branch:
    description: "The head branch that will be used to create the PR"
    default: main
  npm-tag:
    description: "NPM tag (e.g. latest or next)"
    default: latest
  packages:
    description: "Packages to update"
    required: true

outputs:
  has-updates:
    description: "If there are updates"
  branch:
    description: "The branch with the updated packages"
  pr:
    description: "The PR url with the updated packages"

runs:
  using: "node20"
  main: "dist/index.js"