name: "Update SDK"
description: "Reusable workflow for update the SDK packages"

inputs:
  token:
    description: "Github Token"
    default: ${{ github.token }}
  organization:
    description: "Github Organization"
    default: ${{ github.repository_owner }}
  repository:
    description: "Github Repository"
    default: ${{ github.repository }}
  npm-tag:
    description: "NPM tag (e.g. latest or next)"
    default: latest

runs:
  using: "composite"
  main: "dist/index.js"
