name: "SDK Outdated"
description: "Reusable workflow for update the SDK packages"

inputs:
  token:
    description: "Github Token"
    default: ${{ github.token }}
  repository:
    description: "Github Repository"
    default: ${{ github.repository }}
  npm-tag:
    description: "NPM tag (e.g. latest or next)"
    default: latest

runs:
  using: "node20"
  main: "dist/index.js"

steps:
  - name: Debugging
    run: |
      echo "Current working directory: $(pwd)"
      ls -al
      git status
      # Add more debugging commands as needed