name: "SDK Outdated"
description: "Reusable workflow for update the SDK packages"

inputs:
  repository:
    description: "Github Repository"
    default: ${{ github.repository }}
  branch:
    description: "Branch name"
    default: main
  packages:
    description: "Packages to update"
    required: true
  npm-tag:
    description: "NPM tag (e.g. latest or next)"
    default: latest

runs:
  using: "node20"
  main: "dist/index.js"