name: "Link PR to Linear Issues"
description: "Workflow for linking PRs to Linear issues"

inputs:
  repository:
    description: "Github Repository"
    default: ${{ github.repository }}
  pull_number:
    description: "PR number to link to linear issues"
    default: ${{ github.event.client_payload.ref }} 
    required: true
  linear_api_key:
    description: "Linear API key"
    required: true
  github_token:
    description: "Github token"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"