name: Lenient Audit

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      pnpm-version:
        required: true
        type: string

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./setups/node
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}
      - name: Install jq
        run: sudo apt-get install jq
      - run: |
          pnpm audit --prod --json | jq '
            def has_fix: 
              .advisories | to_entries | map(.value.patched_versions != "<0.0.0") | any;
            if has_fix then
              1
            else
              0
            end
          ' > audit_result.txt
          if [ "$(cat audit_result.txt)" -eq "1" ]; then
            echo "Actionable vulnerabilities found"
            exit 1
          else
            echo "No actionable vulnerabilities"
            exit 0
          fi