name: "Docs Hub Check"

on:
  workflow_call:
    inputs:
      docs-src-path:
        description: "the folder where SUMMARY.md lives"
        required: true
        type: string
      spellcheck-config-path:
        description: "the path where the .spellcheck.yml file lives"
        required: true
        type: string
      pre-command:
        description: "a command to run before the jobs"
        required: false
        type: string
        default: ''

jobs: 
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: rojopolis/spellcheck-github-actions@0.34.0
        name: Spellcheck
        with:
          config_path: ${{ inputs.spellcheck-config-path }}
          task_name: SPCheck
