name: Publish Crate

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: "GitHub Token"
        required: true
      CARGO_REGISTRY_TOKEN:
        description: "Token for publishing to the crates.io registry"
        required: true
      SLACK_WEBHOOK_URL:
        description: "Slack Webhook URL"
        required: true

jobs:
  publish-crate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Verify Tag
        run: |
          curl -sSLf "https://github.com/TomWright/dasel/releases/download/v1.24.3/dasel_linux_amd64" -L -o dasel && chmod +x dasel
          mv ./dasel /usr/local/bin/dasel

          cargo_files=($(find . -name "Cargo.toml" -not -path "./Cargo.toml" -exec grep -L -E "publish\s*=\s*false" {} \; | sed 's/^\.\///'))

          for file in "${cargo_files[@]}"
          do
            ./.github/workflows/scripts/verify_tag.sh ${{ github.ref_name }} "$file"
          done

      - name: Publish crate
        uses: katyo/publish-crates@v1
        with:
          publish-delay: 30000
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  notify-slack-action:
    needs: publish-crate
    if: ${{failure()}}
    uses: FuelLabs/github-actions/.github/workflows/notify-slack-action.yml@master
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
