name: Publish Crate

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: "GitHub Token"
        required: true
      CARGO_REGISTRY_TOKEN:
        description: "Token for publishing to the crates.io registry"
        required: true
      SLACK_WEBHOOK_URL:
        description: "Slack Webhook URL"
        required: true

jobs:
  publish-crate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Publish crate
        uses: katyo/publish-crates@v1
        with:
          publish-delay: 30000
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  notify-slack-action:
    needs: cargo-toml-lint
    if: ${{failure()}}
    uses: FuelLabs/github-actions/.github/workflows/notify-slack-action.yml@master
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
